### ISSUE TITLE
Error 400 - Bad Request

### ISSUE THREAD

**Issue by Janaka-Steph** [bitcoinjs/regtest-server#4]
Hello

First of all, thank you Daniel for all your amazing work!
I would like to use the regtest server in order to to execute the bitcoinjs-lib integration tests, for me and for educational purposes. 

I managed to connect it with my local regtest bitcoin node and this part seems to work fine. 
Unfortunately any request I do will return error 400 Bad request. So I am deducing that the port is good, server is properly listening on port 80, but do not handle the request. Also, when I do a request, I don't have any log, the server doesn't have any reaction.   

Here is an example of a failing bitcoinjs-lib test
```
 4) bitcoinjs-lib (payments - p2ms)
       can (as P2SH(p2ms)) broadcast as an output, and be spent as an input:
     Error: Bad Request
      at /Users/steph/Desktop/BitcoinJS/bitcoinjs-lib/node_modules/dhttp/200.js:11:23
      at done (node_modules/dhttp/index.js:13:19)
      at handle (node_modules/dhttp/index.js:31:7)
      at ClientRequest.<anonymous> (node_modules/dhttp/index.js:45:5)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
      at Socket.socketOnData (_http_client.js:441:20)
      at addChunk (_stream_readable.js:283:12)
      at readableAddChunk (_stream_readable.js:264:11)
      at Socket.Readable.push (_stream_readable.js:219:10)
      at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Here are my environnement variables (I have just added a prefix) 
```
export REGTEST_SERVER_RPC="http://localhost:18443"
export REGTEST_SERVER_RPCCOOKIE="../.cookie"
export REGTEST_SERVER_RPCBATCHSIZE=""
export REGTEST_SERVER_RPCCONCURRENT=""
export REGTEST_SERVER_ZMQ="tcp://127.0.0.1:30001"
export REGTEST_SERVER_INDEXDB="../leveldbData"
export REGTEST_SERVER_KEYDB="../.keysDB"
```

Here is my bitcoin.conf: https://pastebin.com/x2LNnmua

Let me know if you need additional information. 
Thank you.

**Comment by Janaka-Steph** [comment]
Ok sorry for disturbing, I just have forgotten two slashes after 'http:' in _regtest.js...
`const APIURL = 'http://localhost/1'`
:/
